server:
  port: 1001
spring:
  main:
    banner-mode: off
  application:
    name: USERDETAILS-SERVICE
    
#database configuration
  data:
    mongodb:
      database: MyApplication
      host: localhost

#eureka configuration
eureka:
  client:
    service-url:
      defaultzone : http://localhost:8761/eureka