server:
  port: 1005
  
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MyApplication
    username: root
    password: megha123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        
#schema generation
    generate-ddl: true
    hibernate:
      ddl-auto: update
      
  main:
    banner-mode: off
  application:
    name: IDENTITY-SERVICE  
    
eureka:
  client:
    service-url:
      defaultzone : http://localhost:8761/eureka
  instance:
    ip-address: true
